### ISSUE TITLE
Allow users to load their own installers

### ISSUE THREAD

**Issue by OrJDev** [OrJDev/create-jd-app#1]
## Allow users to load their own installers

So if you took a look at the code you could see that jd installers are very flexible and easy to modify / create

### Installer for example
```ts
import { IInstaller } from "create-jd-app/types";

const config: IInstaller = (ctx) => ({
  files: [
    // copy from /files/entryClient.txt to the user-project/src/entry-client.tsx
    {
      path: `${__dirname}/files/entryClient.txt`,
      to: `${ctx.userDir}/src/entry-client.tsx`,
    },
  ],
  // this installer includes npm packages, and can use the context to change pkgs / versions
    "examplePackageName": {
      customVersion:
        ctx.installers.includes("dependOn") ? "1.0.0" : "latest",
    }
  },
});

export default config;
```

so I was wondering wether I should allow users to load their own installers,

#### Creating A Project
```bash
npm create jd-app@latest
```
And custom installers (user's installers) should appear here aswell

#### Managing Installers
```bash
npx create-jd-app@latest -s
```
and then installers menu will pop up and user can choose where should jd-app import his installers from, ofc manage which ones will be ignored and maybe more cool things.

**Comment by OrJDev** [comment]
will reopen when i have time.

**Comment by NathanPip** [comment]
I really like this idea. Wondering if I could lend a hand?

**Comment by OrJDev** [comment]
> I really like this idea. Wondering if I could lend a hand?

This needs to be looked at more to see how can we integrate it with the current api, but yes all prs are appreciated even if you just start working on it
