### ISSUE TITLE
npm install error

### ISSUE THREAD

**Issue by matsumoto-aqua** [OrJDev/create-jd-app#104]
Hi, when I try to npm install,
I got the following error

> npm create jd-app@latest

? What is the name of the app? test-app
? Will you deploy this project to vercel? If so, how None

? What should we use for this app? AuthJS, Prisma, TailwindCSS, tRPC
√ Initialized 4 installers
√ Modified project

Using NPM as package manager
√ Installed dependencies
√ Ran queued commands

        cd test-app
        npm run push    // pushes db to Prisma
        npm run dev

> cd test-app

> npm install

npm ERR! code ERESOLVE
npm ERR! ERESOLVE could not resolve
npm ERR!
npm ERR! While resolving: solid-start-trpc@0.0.16
npm ERR! Found: solid-start@0.3.8
npm ERR! node_modules/solid-start
npm ERR!   solid-start@"^0.3.7" from the root project
npm ERR!   peer solid-start@"^0.3.7" from @solid-mediakit/auth@1.0.3
npm ERR!   node_modules/@solid-mediakit/auth
npm ERR!     @solid-mediakit/auth@"^1.0.3" from the root project
npm ERR!   2 more (@solid-mediakit/trpc, solid-start-node)
npm ERR!
npm ERR! Could not resolve dependency:
npm ERR! peer solid-start@"^0.2.1" from solid-start-trpc@0.0.16
npm ERR! node_modules/solid-start-trpc
npm ERR!   solid-start-trpc@"^0.0.16" from the root project
npm ERR!
npm ERR! Conflicting peer dependency: solid-start@0.2.32
npm ERR! node_modules/solid-start
npm ERR!   peer solid-start@"^0.2.1" from solid-start-trpc@0.0.16
npm ERR!   node_modules/solid-start-trpc
npm ERR!     solid-start-trpc@"^0.0.16" from the root project
npm ERR!
npm ERR! Fix the upstream dependency conflict, or retry
npm ERR! this command with --force or --legacy-peer-deps
npm ERR! to accept an incorrect (and potentially broken) dependency resolution.

**Comment by OrJDev** [comment]
Ah yes i may knkw what that is, will try and push a fix asap

**Comment by OrJDev** [comment]
https://github.com/OrJDev/create-jd-app/commit/9b01d49fd6f9cc1bbd7c9f25805ed87da95c0edd

please reopen if you still face this issue
