### ISSUE TITLE
When generating TRPC app, it uses a dependency that is not open-source (source available anywhere)

### ISSUE THREAD

**Issue by apatrida** [OrJDev/create-jd-app#106]
The dependency used by the generated code, `@solid-mediakit/trpc` is not found in space nor time.

This is similar to the archived `https://github.com/OrJDev/solid-trpc`.

So where is this dependency found?  It is private source unless the https://www.npmjs.com/package/@solid-mediakit/trpc?activeTab=readme points to a Github that is visible.

What's the deal here?

**Comment by OrJDev** [comment]
It is a part of a project called mediakit, mediakit's source code currently isn't public as it has a few packages under development, mediakit is basically a repo that includes many useful utilities for solid, like auth trpc etc, it will soon be public, but you can read the source code of the package via npm's code explorer if you have any concerns

**Comment by OrJDev** [comment]
https://www.npmjs.com/package/@solid-mediakit/trpc?activeTab=code
