### ISSUE TITLE
TypeError: __vite_ssr_import_0__.SolidAuth is not a function

### ISSUE THREAD

**Issue by voxel-8** [OrJDev/create-jd-app#115]
Hello,
I ran npm run dev from npm create jd-app@latest and got the following error.

`? What is the name of the app? my-app
? Will you deploy this project to vercel? If so, how None
? What should we use for this app? AuthJS, Prisma, TailwindCSS, tRPC
        cd my-app
        npm run push    // pushes db to Prisma
        npm run dev

>npm run push
> prisma db push
>npm run dev

8:22:44 [vite] Error when evaluating SSR module /src/routes/api/auth/[...solidauth].ts?pick=GET:
|- TypeError: __vite_ssr_import_0__.SolidAuth is not a function
    at eval (C:/project/my-app/src/routes/api/auth/[...solidauth].ts?pick=GET:10:27)
    at async instantiateModule (file:///C:/project/my-app/node_modules/vinxi/node_modules/vite/dist/node/chunks/dep-bb8a8339.js:56052:9)

[h3] [unhandled] TypeError: __vite_ssr_import_0__.SolidAuth is not a function
    at eval (C:/project/my-app/src/routes/api/auth/[...solidauth].ts?pick=GET:10:27)
    at async instantiateModule (file:///C:/project/my-app/node_modules/vinxi/node_modules/vite/dist/node/chunks/dep-bb8a8339.js:56052:9) {
  cause: TypeError: __vite_ssr_import_0__.SolidAuth is not a function
      at eval (C:/project/my-app/src/routes/api/auth/[...solidauth].ts?pick=GET:10:27)
      at async instantiateModule (file:///C:/project/my-app/node_modules/vinxi/node_modules/vite/dist/node/chunks/dep-bb8a8339.js:56052:9),
  statusCode: 500,
  fatal: false,
  unhandled: true,
  statusMessage: undefined,
  data: undefined
}`

**Comment by OrJDev** [comment]
Did you update the `.env` file? You should have updated the Discord client id and Discord client secret. If so:

Can you create a video or share the output project so i can take a look at? That's odd it created a project for me.

**Comment by voxel-8** [comment]
I tried setting the Discord client ID and Discord client secret and the result was the same.
When you reload, the green screen appears for a moment.
![err0306](https://github.com/OrJDev/create-jd-app/assets/162107209/2ada0d3e-e198-429a-be63-63b713c63a3d)

**Comment by OrJDev** [comment]
Please upload the output project to a repo and send it here so i can take a look

**Comment by voxel-8** [comment]
Sorry, I'm not familiar with github.
Removed my Discord account settings and
I zipped the entire project and uploaded it to Mega.

https://mega.nz/file/Rf91FZLY#ZF29rcsVbTtHrBqeyV0Plw758T7IKXasyx2nbtg5-q0

**Comment by OrJDev** [comment]
This was fixed in the new version, it seems like the api handler used incorrect import

https://github.com/OrJDev/create-jd-app/commit/e0a2ce7a5a997e5fd9fdbf45dfdb10de14f9a266

replace this in ```/src/routes/api/auth/[...solidauth].ts```

```diff
- import { SolidAuth } from "@solid-mediakit/trpc/handler";
+ import { SolidAuth } from "@solid-mediakit/auth";
```
