### ISSUE TITLE
query client should not be shared between requests

### ISSUE THREAD

**Issue by shiro** [OrJDev/create-jd-app#119]
As far as I'm aware, sharing an instance of `QueryClient` could result in leaking of user-specific data to other requests, since the cache is shared (correct me if I'm wrong).

The [official tanstack example](https://tanstack.com/query/latest/docs/framework/solid/examples/solid-start-streaming) also re-creates the client on every request.

Suggested fix: update `src/app.tsx` to:
```ts
export default function App() {
  const queryClient = new QueryClient({
    // ...
  });

  // ...
}
```

**Comment by OrJDev** [comment]
> As far as I'm aware, sharing an instance of `QueryClient` could result in leaking of user-specific data to other requests, since the cache is shared (correct me if I'm wrong).
> 
> 
> 
> The [official tanstack example](https://tanstack.com/query/latest/docs/framework/solid/examples/solid-start-streaming) also re-creates the client on every request.
> 
> 
> 
> Suggested fix: update `src/app.tsx` to:
> 
> ```ts
> 
> export default function App() {
> 
>   const queryClient = new QueryClient({
> 
>     // ...
> 
>   });
> 
> 
> 
>   // ...
> 
> }
> 
> ```

Thank you for this, ye i think we should use whatever is being recommended by tanstack, if you want to make a pr go ahead if not i will make one once im available to.

**Comment by OrJDev** [comment]
fixed in https://github.com/OrJDev/create-jd-app/commit/97c93290ecf8c3fc25cc87b2247229c816ae7e57
