### ISSUE TITLE
TSError: Prisma types referenced even when unselected

### ISSUE THREAD

**Issue by Alex23rodriguez** [OrJDev/create-jd-app#17]
**Problem:**
The api route `[...solidauth].ts` has typescript errors upon creation

**Steps to reproduce:**
create a new jd application with the following settings (maybe flexible):
- [X] Vercel
- [X] SolidAuth
- [X] TailwindCSS
(notably, Prisma is _not_ selected)  

head over to `src/routes/api/auth/[...solidauth].ts`. Notice that the first line imports the type `User` from prisma, even though prisma is not installed.

**Comment by OrJDev** [comment]
Ohh my bad will fix this today.
