### ISSUE TITLE
Start script fails to run when using prisma.

### ISSUE THREAD

**Issue by eli-rich** [OrJDev/create-jd-app#23]
# Prisma `__dirname is not defined` when running `pnpm start`

Tested with both `npm` and `pnpm`. I also tried removing the postinstall script. That did not resolve the issue.

## To Reproduce

```sh
pnpm  create jd-app@latest
# name does not matter
# select No when asked if you will be deploying to vercel
# select prisma
cd my-app
pnpm push
pnpm build
pnpm start
```

Full stdout: [sourcebin link](https://sourceb.in/p6chPVzxzx)
Also attached below
[error.txt](https://github.com/OrJDev/create-jd-app/files/10116117/error.txt)

## Manual Fix

I was able to fix this simply by adding the following to server.js near the top (before the first `var` is declared.):

```js
const __dirname = dirname(fileURLToPath(import.meta.url));
```

## My Specs:

- Macbook Pro Intel
- OS: `Ventura 13.0.1`
- Node: `v19.1.0`
- `uname -a`: `Darwin Elis-MacBook-Pro.local 22.1.0 Darwin Kernel Version 22.1.0: Sun Oct 9 20:14:54 PDT 2022; root:xnu-8792.41.9~2/RELEASE_X86_64 x86_64`

**Comment by OrJDev** [comment]
ah yes i will have to search for an alternative, however when using adapters like vercel, netlify etc it shouldn't happen and the build can be used in production

**Comment by OrJDev** [comment]
Closing for now because its not really create jd app related but solid start's known eror.

**Comment by OrJDev** [comment]
this was solved in https://github.com/OrJDev/create-jd-app/commit/2c9ee1afe463a8c95757a9ddb4f314cd7b83cb9c
