### ISSUE TITLE
Externalizing Prisma

### ISSUE THREAD

**Issue by binajmen** [OrJDev/create-jd-app#26]
I was impacted by this issue https://github.com/solidjs/solid-start/issues/398

You might want to add these lines when installing Prisma:
```diff
import solid from "solid-start/vite";
import { defineConfig } from "vite";
import dotenv from "dotenv";

export default defineConfig(() => {
  dotenv.config();
  return {
    plugins: [solid({ ssr: true })],
+    ssr: {
+      external: ["@prisma/client"],
+    },
  };
});
```

As I'm not sure how to handle that, I will not create a PR for this one.

**Comment by OrJDev** [comment]
to be checked, seems to work fine for me
