### ISSUE TITLE
Include user.id on session

### ISSUE THREAD

**Issue by mattddean** [OrJDev/create-jd-app#31]
create-t3-app extends NextAuth's session to include the user's id. I think this project should consider doing the same.

https://github.com/t3-oss/create-t3-app/issues/176
https://github.com/t3-oss/create-t3-app/pull/180/files

**Comment by OrJDev** [comment]
Sure will do so when i arrive home

**Comment by OrJDev** [comment]
https://github.com/OrJDev/create-jd-app/releases/tag/v0.1.5
