### ISSUE TITLE
Getting started, couple of issues 👀 

### ISSUE THREAD

**Issue by donferi** [OrJDev/create-jd-app#45]
Hello, I tried to initialize an app using this starter kit and got a few issues, would love some guidance! Not sure what I'm doing wrong!

I started a new project with the following config:
```
Deploy on vercel? None
What should we use?
- NextAuth
- Prisma
- Tailwind
- tRPC
```

After that I did:
```
npm run push
npm run build
npm run start   (I'm aware this is not the dev flow)
```

I got hit with this error:

```
> start
> solid-start start --port 3000

 solid-start start
 version  0.2.18
 adapter  node


  ➜  Page Routes:
     └─ http://localhost:3000/

  ➜  API Routes:
     ┌─  http://localhost:3000/api/auth/*solidauth GET | POST
     └─  http://localhost:3000/api/trpc/:trpc GET | POST

file:///private/var/folders/dv/2y16mb5d4xx4z2nbsg57mmbh0000gn/T/tmp.W0vnpZtg/my-app/dist/server.js:47022
                import_path2.default.join(__dirname, "../query-engine-darwin");
                                          ^

ReferenceError: __dirname is not defined in ES module scope
This file is being treated as an ES module because it has a '.js' file extension and '/private/var/folders/dv/2y16mb5d4xx4z2nbsg57mmbh0000gn/T/tmp.W0vnpZtg/my-app/package.json' contains "type": "module". To treat it as a CommonJS script, rename it to use the '.cjs' file extension.
    at file:///private/var/folders/dv/2y16mb5d4xx4z2nbsg57mmbh0000gn/T/tmp.W0vnpZtg/my-app/dist/server.js:47022:29
    at requireRuntime (file:///private/var/folders/dv/2y16mb5d4xx4z2nbsg57mmbh0000gn/T/tmp.W0vnpZtg/my-app/dist/server.js:59687:3)
    at file:///private/var/folders/dv/2y16mb5d4xx4z2nbsg57mmbh0000gn/T/tmp.W0vnpZtg/my-app/dist/server.js:59717:7
    at requireClient$1 (file:///private/var/folders/dv/2y16mb5d4xx4z2nbsg57mmbh0000gn/T/tmp.W0vnpZtg/my-app/dist/server.js:59902:3)
    at requireClient (file:///private/var/folders/dv/2y16mb5d4xx4z2nbsg57mmbh0000gn/T/tmp.W0vnpZtg/my-app/dist/server.js:59913:7)
    at file:///private/var/folders/dv/2y16mb5d4xx4z2nbsg57mmbh0000gn/T/tmp.W0vnpZtg/my-app/dist/server.js:59918:21
    at ModuleJob.run (node:internal/modules/esm/module_job:193:25)
    at async Promise.all (index 0)
    at async ESMLoader.import (node:internal/modules/esm/loader:530:24)
```

Did some digging and was able to fix it following this comment https://github.com/solidjs/solid-start/issues/398#issuecomment-1303842877

Now `npm run build` and `npm run start` work fine, however, something is off as my requests take 7 seconds (on dev they are mostly instant).

I haven't touched any of the code yet:

```
❯ time curl localhost:3000 >/dev/null
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
100  3562    0  3562    0     0    498      0 --:--:--  0:00:07 --:--:--   723
curl localhost:3000 > /dev/null  0.00s user 0.00s system 0% cpu 7.148 total
```

Thank you so much for this awesome setup! I'm just not sure what I'm doing wrong 😅

**Comment by OrJDev** [comment]
Hey there, the first issue is now fixed - https://github.com/OrJDev/create-jd-app/commit/2c9ee1afe463a8c95757a9ddb4f314cd7b83cb9c

The second issue is not actually an issue but if you go to `utils/trpc.ts`

You will see that the getBaseUrl function has this line:

```ts
if(process.env.NODE_ENV === "production") return "..."
```

If you are running it locally using the `npm run start` command you have to comment this out.

That is because the getBaseUrl function can't tell wether it is actually a production mode or you are running `npm run start` - both will set the node env to production so that confuses this function. In production don't forget to add the line above and return the url of your deployment

**Comment by OrJDev** [comment]
Does the above close your issue? 

If so, may i close this?

**Comment by OrJDev** [comment]
Reopen if the above doesn't solve your issue.

**Comment by donferi** [comment]
@OrJDev Sorry for the late reply, we had an ice storm over here. Thanks for the quick fix and letting me know what I missed. I appreciate it. 🙇

**Comment by OrJDev** [comment]
> @OrJDev Sorry for the late reply, we had an ice storm over here. Thanks for the quick fix and letting me know what I missed. I appreciate it. 🙇 

No problem, glad i could help
