### ISSUE TITLE
Account model missing `expires_in`

### ISSUE THREAD

**Issue by tmns** [OrJDev/create-jd-app#46]
Created a project today choosing Prisma and (Next)Auth and immediately ran into difficulties trying to set up Google & Discord providers (didn't try any others).

Upon successful authentication on the provider side, I would receive the following error:

<details>
<summary>Click for error</summary>
<pre>AdapterError: 
Invalid `p.account.create()` invocation in
/node_modules/@next-auth/prisma-adapter/dist/index.js:19:42

  16 },
  17 updateUser: ({ id, ...data }) => p.user.update({ where: { id }, data }),
  18 deleteUser: (id) => p.user.delete({ where: { id } }),
→ 19 linkAccount: (data) => p.account.create({
       data: {
         provider: 'discord',
         type: 'oauth',
         providerAccountId: '...',
         access_token: '...',
         expires_in: 604800,
         ~~~~~~~~~~
         refresh_token: '...',
         scope: 'email identify',
         token_type: 'bearer',
         userId: '...'
       }
     })

Unknown arg `expires_in` in data.expires_in for type AccountUncheckedCreateInput. Did you mean `expires_at`? Available args:
type AccountUncheckedCreateInput {
  id?: String
  userId: String
  type: String
  provider: String
  providerAccountId: String
  refresh_token?: String | Null
  access_token?: String | Null
  expires_at?: Int | Null
  token_type?: String | Null
  scope?: String | Null
  id_token?: String | Null
  session_state?: String | Null
}
    at acc.<computed> (file:///node_modules/@auth/core/lib/init.js:133:31)
    at async handleLogin (file:///node_modules/@auth/core/lib/callback-handler.js:172:13)
    at async Module.callback (file:///node_modules/@auth/core/lib/routes/callback.js:46:50)
    at async AuthInternal (file:///node_modules/@auth/core/lib/index.js:52:38)
    at async Auth (file:///node_modules/@auth/core/index.js:95:30)
    at async file:///node_modules/@auth/solid-start/index.js:39:17
    at async Object.GET [as handler] (file:///node_modules/@auth/solid-start/index.js:61:14)
    at async eval (/node_modules/solid-start/api/middleware.ts:23:16)
    at async eval (/node_modules/solid-start/entry-server/StartServer.tsx:41:12)
    at async devFetch (file:///node_modules/solid-start/dev/server.js:46:12)
    at async startHandler (file:///node_modules/solid-start/dev/server.js:115:20)
[auth][error][AdapterError]: Read more at https://errors.authjs.dev#adaptererror
</pre>
</details>

The error seems to suggest that the Prisma Account model is missing the `expires_in` column, which is included in the auth object returned from the provider and used to create the new record. Instead, [the model is only set up with an `expires_at` column](https://github.com/OrJDev/create-jd-app/blob/a9307982edd2edf049876210eb4390dea0be6f96/src/installers/Prisma/utils/getSchema.ts#L20-L35).

I fixed it by simply creating a migration to add the missing column. I'm guessing a similar fix for the repo itself would be to add that column to the model linked above.

It's puzzling though because the model is defined the same way in `create-t3-app` but it works fine there 🤨 So maybe some discrepancy between next auth & solid auth?

**Comment by AshSimmonds** [comment]
Not a 100% authority but as far as I can tell this model has only been tested with github.  
  
I had to do semi-significant changes to make Discord work, intend to PR them back but am travelling and mostly on mobile device. Search `solidstart-17`, I may or may not have pushed branch feature changes there  can't recall.

**Comment by tmns** [comment]
Interesting, thanks. The only change I had to make to get Discord working was the one described above (adding `expires_in` to the model) -- maybe things have changed a bit since you worked on it.

**Comment by OrJDev** [comment]
> Interesting, thanks. The only change I had to make to get Discord working was the one described above (adding `expires_in` to the model) -- maybe things have changed a bit since you worked on it.

Yes this is in the core of authJs, different providers require different models. This model is for google, github, etc

**Comment by OrJDev** [comment]
> Interesting, thanks. The only change I had to make to get Discord working was the one described above (adding `expires_in` to the model) -- maybe things have changed a bit since you worked on it.

https://github.com/OrJDev/create-jd-app/commit/e4d74cf18e14501a00d7228ec4765690768ae2e5

also added a note for you so it will be easier next time

**Comment by OrJDev** [comment]
> > Interesting, thanks. The only change I had to make to get Discord working was the one described above (adding `expires_in` to the model) -- maybe things have changed a bit since you worked on it.
> 
> 
> 
> https://github.com/OrJDev/create-jd-app/commit/e4d74cf18e14501a00d7228ec4765690768ae2e5
> 
> 
> 
> also added a note for you so it will be easier next time

Actually now the default provider is Discord as i don't see many People who use Github and it causes issues for people who want to use other Providers:

https://github.com/OrJDev/create-jd-app/commit/f1b3b0a757fc607f66a5da258b3172f6839327ec

**Comment by tmns** [comment]
Nice.. it does still strike me as a bit odd though that the Discord adapter seems to work in T3 (NextAuth) even without such a modification. Since it works there, I wonder if it's something that could be fixed in `@auth/solid-start`. 🤔

**Comment by OrJDev** [comment]
it is not within `@auth/solid-start` itself. 
it is within the new core of AuthJS, you could make an issue and ask why this happens at https://github.com/nextauthjs/next-auth

**Comment by OrJDev** [comment]
> it is not within `@auth/solid-start` itself. 
> 
> it is within the new core of AuthJS, you could make an issue and ask why this happens at https://github.com/nextauthjs/next-auth

Actually here is the answer for this issue: https://github.com/nextauthjs/next-auth/issues/6538#issuecomment-1407505542

**Comment by tmns** [comment]
Yep stumbled across that afterward too. At the end of the day simply changing the model was the right suggestion to quickly get things working 👍 

Notice though that the breaking provider in the linked issue there is Google. Indeed I originally saw this error happening with Google as well as Discord. However, I went back and tried again, and Google seemed to work even without `expires_in` 🤷‍♂️
