### ISSUE TITLE
build gets stuck while deploying on vercel with pnpm

### ISSUE THREAD

**Issue by aidanaden** [OrJDev/create-jd-app#5]
When trying to deploy to vercel with pnpm, the build process gets stuck indefinitely

![image](https://user-images.githubusercontent.com/26812563/201824815-e65c4b54-a606-47bd-be31-50c0faf92ed3.png)

**Comment by OrJDev** [comment]
Hey there, this is unrelated to pnpm or your package manager, this is not related to jd either. 
Its an actual bug that Nikhil (the creator of solid start) is working on these days. You can find more info in here:

https://github.com/solidjs/solid-start/issues/383

Sometimes it helps to create new repo, reinstall the modules and recreate vercel project.

**Comment by OrJDev** [comment]
Also as i wrote in the bug report,
You could build and deploy using the vercel cli and it won't get stuck, however you cannot build it locally when using Prisma. 
So unless you are using Prisma try building and deploying using the vercel cli

**Comment by aidanaden** [comment]
> Hey there, this is unrelated to pnpm or your package manager, this is not related to jd either. Its an actual bug that Nikhil (the creator of solid start) is working on these days. You can find more info in here:
> 
> [solidjs/solid-start#383](https://github.com/solidjs/solid-start/issues/383)
> 
> Sometimes it helps to create new repo, reinstall the modules and recreate vercel project.

seems like yarn works without any issue tho? solved the issue by using yarn instead for now :)

**Comment by OrJDev** [comment]
Oh that's very important to know, could you post this in the issue i mentioned above? It might be something with the packages after all

**Comment by OrJDev** [comment]
But just so you know its not pnpm specifically, 
using npm might work sometimes and sometimes not, so the package manager is not the issue but some packages cause this issue

**Comment by aidanaden** [comment]
> 

ahh i see - interesting that yarn works without issue

**Comment by aidanaden** [comment]
> But just so you know its not pnpm specifically, using npm might work sometimes and sometimes not, so the package manager is not the issue but some packages cause this issue

ahh i see - interesting that yarn works without issue
