### ISSUE TITLE
Allow user to create app in the directory they are currently in

### ISSUE THREAD

**Issue by NathanPip** [OrJDev/create-jd-app#51]
It would be nice to be able to create the app in the directory you are currently in by specifying (.) as the project name. Many CLI apps allow this and it has become habit of mine to create the directory for my projects before running any cli commands in them. 

And thanks for the hard work! You've saved me and many others hours in scaffolding time.

**Comment by NathanPip** [comment]
#52

**Comment by OrJDev** [comment]
> It would be nice to be able to create the app in the directory you are currently in by specifying (.) as the project name. Many CLI apps allow this and it has become habit of mine to create the directory for my projects before running any cli commands in them.
> 
> And thanks for the hard work! You've saved me and many others hours in scaffolding time.

Thanks and as the note i left there, instead of changing the name, we should have a `current` flag

so i just added this flag https://github.com/OrJDev/create-jd-app/commit/ca0fd9db029361a2c1fae82436047e0d140fc93d
