### ISSUE TITLE
Query Client not exported

### ISSUE THREAD

**Issue by statusunknown418** [OrJDev/create-jd-app#55]
So I've just created a base app with trpc enabled and I'm getting an error saying.

<img width="859" alt="Screenshot 2023-02-17 at 13 27 16" src="https://user-images.githubusercontent.com/74371045/219751249-b48f4cc1-d161-4ab1-a0f7-9c48bf004153.png">

I think the new `QueryClient` should either be `trpc.useContext()` or `QueryClient from @tanstack/solid-query`

**Comment by OrJDev** [comment]
Oh i see, did you say yes when it asked you if you want to use ssr with trpc?

**Comment by statusunknown418** [comment]
Yep, I think the config changes for ssr

**Comment by OrJDev** [comment]
> Yep, I think the config changes for ssr

@tanstack/solid-query shouldn't be installed when choosing ssr, can you create a repo with the full output files?

**Comment by OrJDev** [comment]
> > Yep, I think the config changes for ssr
> 
> @tanstack/solid-query shouldn't be installed when choosing ssr, can you create a repo with the full output files? 

https://github.com/OrJDev/create-jd-app/blob/main/src/installers/tRPC/index.ts#L43

**Comment by statusunknown418** [comment]
You mean selecting all the installers and enabling ssr?

**Comment by OrJDev** [comment]
> You mean selecting all the installers and enabling ssr?

No like, create a repo with what create jd app created for you

**Comment by statusunknown418** [comment]
sure, it's here https://github.com/AlvaroAquijeDiaz/jd-app-demo

**Comment by OrJDev** [comment]
> sure, it's here https://github.com/AlvaroAquijeDiaz/jd-app-demo

```bash
rm -rf node_modules 
pnpm install
```


Would this work for you

**Comment by statusunknown418** [comment]
> > sure, it's here https://github.com/AlvaroAquijeDiaz/jd-app-demo
> 
> ```shell
> rm -rf node_modules 
> pnpm install
> ```
> 
> Would this work for you

error still showing up though

**Comment by OrJDev** [comment]
> > > sure, it's here https://github.com/AlvaroAquijeDiaz/jd-app-demo
> 
> > 
> 
> > ```shell
> 
> > rm -rf node_modules 
> 
> > pnpm install
> 
> > ```
> 
> > 
> 
> > Would this work for you
> 
> 
> 
> error still showing up though

That is weird because `@tanstack/solid-query` doesn't even seem to appear in package.json, could you try using different package manager, like npm.

```bash
rm -rf node_modules
npm install
```

Also make sure to restart the ts server after that

**Comment by OrJDev** [comment]
Hey there, 
Could you give an update on that?

**Comment by statusunknown418** [comment]
Hey, I'll be looking at it tomorrow, haven't had the opportunity yet

**Comment by statusunknown418** [comment]
> Hey there, Could you give an update on that?

<img width="694" alt="Screenshot 2023-02-20 at 17 39 11" src="https://user-images.githubusercontent.com/74371045/220208299-deb00808-2f00-4630-837c-15c1b566382a.png">

got this error while trying to use `npm`, weird

**Comment by statusunknown418** [comment]
using `--legacy-peer-deps` solves both issues

**Comment by statusunknown418** [comment]
however is there a reason why @adeora/solid-query is used instead of the plain @tanstack/solid-query? or the `useContext` shipped with `tRPC v10`?

**Comment by OrJDev** [comment]
> however is there a reason why @adeora/solid-query is used instead of the plain @tanstack/solid-query? or the `useContext` shipped with `tRPC v10`?

Aryan is the guy who created solid query, this is a patched package that supports server side rendering. The normal solid query doesn't support that

**Comment by OrJDev** [comment]
Also i found the error, link dependencies are not being installed, there are multiple opened issues for this

https://github.com/pnpm/pnpm/issues/4842

https://github.com/pnpm/pnpm/issues/5523

**Comment by OrJDev** [comment]
closing, check the issues above to see the progress, will update when it is fixed.
