### ISSUE TITLE
tRPC SSR adapter doesn't work in vercel production enviornment.

### ISSUE THREAD

**Issue by shivanshubisht** [OrJDev/create-jd-app#60]
It's unclear whether the problem lies with the create jd-app or tRPC, but the tRPC server-side rendering (SSR) feature functions properly only in a local development environment. However, it fails to operate when deployed to Vercel.

**Comment by OrJDev** [comment]
> It's unclear whether the problem lies with the create jd-app or tRPC, but the tRPC server-side rendering (SSR) feature functions properly only in a local development environment. However, it fails to operate when deployed to Vercel.

 Could you share your utils/trpc.ts file? I believe you just forgot to update the production url

**Comment by shivanshubisht** [comment]
Ah, I didn't see the production URL. Maybe we could add an option to set the production URL directly in the .env file?

**Comment by shivanshubisht** [comment]
```
import { QueryClient } from '@adeora/solid-query';
import type { IAppRouter } from '~/server/trpc/router/_app';
import { createTRPCSolidStart } from 'solid-trpc';
import { httpBatchLink } from '@trpc/client';

const getBaseUrl = () => {
  if (typeof window !== 'undefined') return '';
  // replace example.com with your actual production url
  if (process.env.NODE_ENV === 'production') return 'https://letsgo.xyz';
  return `http://localhost:${process.env.PORT ?? 3000}`;
};

export const trpc = createTRPCSolidStart<IAppRouter>({
  config() {
    return {
      links: [
        httpBatchLink({
          url: `${getBaseUrl()}/api/trpc`,
        }),
      ],
    };
  },
});

export const queryClient = new QueryClient();
```
Even after updating the production URL, tRPC is still not SSRing.

**Comment by OrJDev** [comment]
> ```
> import { QueryClient } from '@adeora/solid-query';
> import type { IAppRouter } from '~/server/trpc/router/_app';
> import { createTRPCSolidStart } from 'solid-trpc';
> import { httpBatchLink } from '@trpc/client';
> 
> const getBaseUrl = () => {
>   if (typeof window !== 'undefined') return '';
>   // replace example.com with your actual production url
>   if (process.env.NODE_ENV === 'production') return 'https://letsgo.xyz';
>   return `http://localhost:${process.env.PORT ?? 3000}`;
> };
> 
> export const trpc = createTRPCSolidStart<IAppRouter>({
>   config() {
>     return {
>       links: [
>         httpBatchLink({
>           url: `${getBaseUrl()}/api/trpc`,
>         }),
>       ],
>     };
>   },
> });
> 
> export const queryClient = new QueryClient();
> ```
> 
> Even after updating the production URL, tRPC is still not SSRing.

that is odd, what do you mean not ssring?

**Comment by shivanshubisht** [comment]
trpc query is rendered in loading state when loading the page while javascript is disabled, even though it works in dev environment.

**Comment by OrJDev** [comment]
> trpc query is rendered in loading state when loading the page while javascript is disabled, even though it works in dev environment.

you shouldn't access .isLoading when ssring, you should trigger suspense by calling .data (this will trigger the solidjs resource behind the hood)

Wrap your comp with

```ts
<Show when={trpcQuery.data}>
{...}
</Show>
```

**Comment by OrJDev** [comment]
> > trpc query is rendered in loading state when loading the page while javascript is disabled, even though it works in dev environment.
> 
> 
> 
> you shouldn't access .isLoading when ssring, you should trigger suspense by calling .data (this will trigger the solidjs resource behind the hood)
> 
> 
> 
> Wrap your comp with
> 
> 
> 
> ```ts
> 
> <Show when={trpcQuery.data}>
> 
> {...}
> 
> </Show>
> 
> ```

Also if you are having issues with the vercel url, someone in the solid-start's discord suggested to use the vercel url environment variable:

```ts
const getBaseUrl = () => {
  if (typeof window !== "undefined") return ""; // browser should use relative url
  if (process.env.VERCEL_URL) return `https://${process.env.VERCEL_URL}`; // SSR should use vercel url
  return `http://localhost:${process.env.PORT ?? 3000}`; // dev SSR should use localhost
};
```

**Comment by shivanshubisht** [comment]
> > trpc query is rendered in loading state when loading the page while javascript is disabled, even though it works in dev environment.
> 
> you shouldn't access .isLoading when ssring, you should trigger suspense by calling .data (this will trigger the solidjs resource behind the hood)
> 
> Wrap your comp with
> 
> ```ts
> <Show when={trpcQuery.data}>
> {...}
> </Show>
> ```

I wasn't accesing the isLoading state while ssring, just using loading query as fallback
```{hello.data ?? 'Loading letsGo'}```

**Comment by shivanshubisht** [comment]
> > > trpc query is rendered in loading state when loading the page while javascript is disabled, even though it works in dev environment.
> > 
> > 
> > you shouldn't access .isLoading when ssring, you should trigger suspense by calling .data (this will trigger the solidjs resource behind the hood)
> > Wrap your comp with
> > ```ts
> > <Show when={trpcQuery.data}>
> > 
> > {...}
> > 
> > </Show>
> > ```
> 
> Also if you are having issues with the vercel url, someone in the solid-start's discord suggested to use the vercel url environment variable:
> 
> ```ts
> const getBaseUrl = () => {
>   if (typeof window !== "undefined") return ""; // browser should use relative url
>   if (process.env.VERCEL_URL) return `https://${process.env.VERCEL_URL}`; // SSR should use vercel url
>   return `http://localhost:${process.env.PORT ?? 3000}`; // dev SSR should use localhost
> };
> ```

This fixes the issue for vercel deployments
```if (process.env.VERCEL_URL) return `https://${process.env.VERCEL_URL}`; // SSR should use vercel url```
