### ISSUE TITLE
Rate limiter in non-tRPC mode as middleware

### ISSUE THREAD

**Issue by va3y** [OrJDev/create-jd-app#62]
Right now, when creating a template with a rate limiter without tRPC, the `limit.ts` GET endpoint is [created](https://github.com/OrJDev/create-jd-app/blob/main/src/installers/Upstash%20Ratelimit/index.ts). The file has the basic template to get started, but I'm not sure if that is sensible to create rate limiter as an endpoint. 

My idea is to use Solid Start middleware for this usecase: https://start.solidjs.com/advanced/middleware
We probably want rate limiter to affect every route, as we do with the tRPC case, when we add it to the procedure. 

I can file a PR if that sounds good to you, what do you think? @OrJDev

**Comment by OrJDev** [comment]
> Right now, when creating a template with a rate limiter without tRPC, the `limit.ts` GET endpoint is [created](https://github.com/OrJDev/create-jd-app/blob/main/src/installers/Upstash%20Ratelimit/index.ts). The file has the basic template to get started, but I'm not sure if that is sensible to create rate limiter as an endpoint. 
> 
> 
> 
> My idea is to use Solid Start middleware for this usecase: https://start.solidjs.com/advanced/middleware
> 
> We probably want rate limiter to affect every route, as we do with the tRPC case, when we add it to the procedure. 
> 
> 
> 
> I can file a PR if that sounds good to you, what do you think? @OrJDev

Yes sure that would be great,thank you. Lmk if you face any issue so i will do it later.

**Comment by OrJDev** [comment]
pr was opened, closing this
