### ISSUE TITLE
unable to initialise - Command failed: npm install on installing vite

### ISSUE THREAD

**Issue by szamanr** [OrJDev/create-jd-app#64]
hi! i would love to check out this project but i'm unable to get it running. i'm on linux (ubuntu 20.04), node v16.17.0 and npm 8.15.0. when i run the init script, i'm getting an error related to npm install on vite package.

full output:

```
> npm create jd-app@latest

? What is the name of the app? solid-230225
? Do you want to overwrite this directory? Yes
✔ Emptied directory
? Will you deploy this project to vercel? If so, how None

✔ Copied template files to /home/r/workspace/solid-230225
? What should we use for this app? Prisma, TailwindCSS, tRPC
? Do you want to use SSR with tRPC? Yes

✔ Initialized 3 installers
✔ Modified project

Using NPM as package manager
✖ Couldn't install template dependencies: Command failed: npm install
npm ERR! code ERESOLVE
npm ERR! ERESOLVE unable to resolve dependency tree
npm ERR! 
npm ERR! While resolving: solid-230225@undefined
npm ERR! Found: vite@4.1.4
npm ERR! node_modules/vite
npm ERR!   dev vite@"^4.1.2" from the root project
npm ERR!   peer vite@"*" from solid-start-aws@0.2.22
npm ERR!   node_modules/solid-start-aws
npm ERR!     peerOptional solid-start-aws@"*" from solid-start@0.2.22
npm ERR!     node_modules/solid-start
npm ERR!       solid-start@"^0.2.21" from the root project
npm ERR!       8 more (solid-start-aws, solid-start-cloudflare-pages, ...)
npm ERR!   6 more (solid-start-cloudflare-pages, ...)
npm ERR! 
npm ERR! Could not resolve dependency:
npm ERR! peer vite@"^3.1.8" from solid-start@0.2.22
npm ERR! node_modules/solid-start
npm ERR!   solid-start@"^0.2.21" from the root project
npm ERR!   peer solid-start@"*" from solid-start-aws@0.2.22
npm ERR!   7 more (solid-start-cloudflare-pages, ...)
npm ERR! 
npm ERR! Fix the upstream dependency conflict, or retry
npm ERR! this command with --force, or --legacy-peer-deps
npm ERR! to accept an incorrect (and potentially broken) dependency resolution.
npm ERR! 
npm ERR! See /home/r/.npm/eresolve-report.txt for a full report.

npm ERR! A complete log of this run can be found in:
npm ERR!     /home/r/.npm/_logs/2023-02-25T21_10_07_529Z-debug-0.log

npm ERR! code 1
npm ERR! path /home/r/workspace
npm ERR! command failed
npm ERR! command sh /tmp/npx-7d52fba7.sh

npm ERR! A complete log of this run can be found in:
npm ERR!     /home/r/.npm/_logs/2023-02-25T21_09_56_287Z-debug-0.log
```

**Comment by OrJDev** [comment]
> hi! i would love to check out this project but i'm unable to get it running. i'm on linux (ubuntu 20.04), node v16.17.0 and npm 8.15.0. when i run the init script, i'm getting an error related to npm install on vite package.
> 
> 
> 
> full output:
> 
> 
> 
> ```
> 
> > npm create jd-app@latest
> 
> 
> 
> ? What is the name of the app? solid-230225
> 
> ? Do you want to overwrite this directory? Yes
> 
> ✔ Emptied directory
> 
> ? Will you deploy this project to vercel? If so, how None
> 
> 
> 
> ✔ Copied template files to /home/r/workspace/solid-230225
> 
> ? What should we use for this app? Prisma, TailwindCSS, tRPC
> 
> ? Do you want to use SSR with tRPC? Yes
> 
> 
> 
> ✔ Initialized 3 installers
> 
> ✔ Modified project
> 
> 
> 
> Using NPM as package manager
> 
> ✖ Couldn't install template dependencies: Command failed: npm install
> 
> npm ERR! code ERESOLVE
> 
> npm ERR! ERESOLVE unable to resolve dependency tree
> 
> npm ERR! 
> 
> npm ERR! While resolving: solid-230225@undefined
> 
> npm ERR! Found: vite@4.1.4
> 
> npm ERR! node_modules/vite
> 
> npm ERR!   dev vite@"^4.1.2" from the root project
> 
> npm ERR!   peer vite@"*" from solid-start-aws@0.2.22
> 
> npm ERR!   node_modules/solid-start-aws
> 
> npm ERR!     peerOptional solid-start-aws@"*" from solid-start@0.2.22
> 
> npm ERR!     node_modules/solid-start
> 
> npm ERR!       solid-start@"^0.2.21" from the root project
> 
> npm ERR!       8 more (solid-start-aws, solid-start-cloudflare-pages, ...)
> 
> npm ERR!   6 more (solid-start-cloudflare-pages, ...)
> 
> npm ERR! 
> 
> npm ERR! Could not resolve dependency:
> 
> npm ERR! peer vite@"^3.1.8" from solid-start@0.2.22
> 
> npm ERR! node_modules/solid-start
> 
> npm ERR!   solid-start@"^0.2.21" from the root project
> 
> npm ERR!   peer solid-start@"*" from solid-start-aws@0.2.22
> 
> npm ERR!   7 more (solid-start-cloudflare-pages, ...)
> 
> npm ERR! 
> 
> npm ERR! Fix the upstream dependency conflict, or retry
> 
> npm ERR! this command with --force, or --legacy-peer-deps
> 
> npm ERR! to accept an incorrect (and potentially broken) dependency resolution.
> 
> npm ERR! 
> 
> npm ERR! See /home/r/.npm/eresolve-report.txt for a full report.
> 
> 
> 
> npm ERR! A complete log of this run can be found in:
> 
> npm ERR!     /home/r/.npm/_logs/2023-02-25T21_10_07_529Z-debug-0.log
> 
> 
> 
> npm ERR! code 1
> 
> npm ERR! path /home/r/workspace
> 
> npm ERR! command failed
> 
> npm ERR! command sh /tmp/npx-7d52fba7.sh
> 
> 
> 
> npm ERR! A complete log of this run can be found in:
> 
> npm ERR!     /home/r/.npm/_logs/2023-02-25T21_09_56_287Z-debug-0.log
> 
> ```

The files were copied, run

```bash
npm install --force
npx prisma db push
```

Tho this is not an expected behavior, i will take a look at it.

**Comment by OrJDev** [comment]
fixed in https://github.com/OrJDev/create-jd-app/commit/d9ad1037852fbed8c359ec9f408a7e750badfaa6
