### ISSUE TITLE
AuthJs on Cloudflare Workers

### ISSUE THREAD

**Issue by AlexErrant** [OrJDev/create-jd-app#80]
This isn't an issue exactly, but I had to do some dumb hacky shit to get SolidStart+AuthJs+CloudflareWorkers working, so I created a minimal example repo to demo the process here https://github.com/AlexErrant/SolidStart_AuthJs_CloudflareWorkers

The hacks stemmed mostly from how Cloudflare Workers don't use `process.env` to inject environment variables, [but instead puts them on the fetch parameter](https://developers.cloudflare.com/workers/platform/environment-variables/#environmental-variables-with-module-workers).

(Solid Start uses ["Module Worker" syntax](https://developers.cloudflare.com/workers/runtime-apis/fetch-event/#syntax-module-worker) on Cloudflare Workers, which is important to know when trying to retrieve your secrets.)

Feel free to close since I have no thoughts on how to improve either CreateJDApp or AuthJs's SolidStart package (though NGL, `export const POST = (x: PageEvent) => SolidAuth(authOpts(x.env)).POST(x)` makes me roll my eyes).

**Comment by OrJDev** [comment]
Oh I didn't know that, maybe we can ask the user which solid adapter he wants to use and then update stuff accordingly

**Comment by OrJDev** [comment]
> Oh I didn't know that, maybe we can ask the user which solid adapter he wants to use and then update stuff accordingly

to do in the future, i don't think its urgent for now as it is a minor change.
