### ISSUE TITLE
Error: "route.outlet is not a function" on creating a new jd app

### ISSUE THREAD

**Issue by deshumake** [OrJDev/create-jd-app#82]
Hello, I just created a new jd app, and when running "npm run dev", a server launches, but the website has a big error saying "route.outlet is not a function". What does this mean? Did I install something incorrectly?

**Comment by OrJDev** [comment]
they seemed to broke something in the solidjs router, could you run this and see if it fixes your issue:

```sh
npm install @solidjs/router@latest
```

**Comment by deshumake** [comment]
Yep that fixed it, thanks!
