### ISSUE TITLE
route.outlet is not a function

### ISSUE THREAD

**Issue by Ladvace** [OrJDev/create-jd-app#83]
I initialized a project with trpc, tailwind and AuthJS but when I try starting it with `npm run dev` I got the following error

<img width="1408" alt="image" src="https://user-images.githubusercontent.com/31326058/229453857-5b49acda-653a-410d-8179-bee2c4c7d4c6.png">

**Comment by OrJDev** [comment]
Run

```sh
npm install @solidjs/router@latest
```

**Comment by Ladvace** [comment]
thanks!
