### ISSUE TITLE
Latest Version of Tanstack Solid Query Breaking CreateJD

### ISSUE THREAD

**Issue by developercbs** [OrJDev/create-jd-app#96]
Steps to repdroduce:

1) Run through install steps
2) Install with TRPC and SSR 
3) Run npm install
4) Run dev

Results:

![image](https://user-images.githubusercontent.com/104138761/235350499-67127dc8-7f8f-4d92-ba89-8b5ab210674f.png)

It would seem there is an issue with the alpha version used for Tanstack Solid Query. Rolling back to 4.29 works fine.

**Comment by OrJDev** [comment]
> Steps to repdroduce:
> 
> 
> 
> 1) Run through install steps
> 
> 2) Install with TRPC and SSR 
> 
> 3) Run npm install
> 
> 4) Run dev
> 
> 
> 
> Results:
> 
> 
> 
> ![image](https://user-images.githubusercontent.com/104138761/235350499-67127dc8-7f8f-4d92-ba89-8b5ab210674f.png)
> 
> 
> 
> It would seem there is an issue with the alpha version used for Tanstack Solid Query. Rolling back to 4.29 works fine. 
> 
> 

What is the exact version installed for you? (Check in package-lock)

**Comment by developercbs** [comment]
![image](https://user-images.githubusercontent.com/104138761/235350999-5898a2ae-1239-4b9d-8f24-f381101bfffb.png)

![image](https://user-images.githubusercontent.com/104138761/235351044-f3c6fe9a-cb73-46d1-9ac2-8bcf2f4c4d9c.png)



This is what I have

**Comment by OrJDev** [comment]
> ![image](https://user-images.githubusercontent.com/104138761/235350999-5898a2ae-1239-4b9d-8f24-f381101bfffb.png)
> 
> 
> 
> 
> 
> This is what I have

I think it is not the latest, can you try:

```sh
pnpm install @tanstack/solid-query@alpha```

**Comment by developercbs** [comment]
> > ![image](https://user-images.githubusercontent.com/104138761/235350999-5898a2ae-1239-4b9d-8f24-f381101bfffb.png)
> > This is what I have
> 
> I think it is not the latest, can you try:
> 
> ```shell
> pnpm install @tanstack/solid-query@alpha```
> ```

![image](https://user-images.githubusercontent.com/104138761/235351133-f00327c3-13b7-4bd2-953d-a2a879595924.png)


Same issue on this.

**Comment by OrJDev** [comment]
```sh
pnpm install @tanstack/solid-query@5.0.0-alpha.20
```

fixed the issue,

also locked this solid query version in - https://github.com/OrJDev/create-jd-app/commit/92b6ec6ba94678895fb7b213f47c7941ace75455
