### ISSUE TITLE
Private procedures throwing unauthorized issue

### ISSUE THREAD

**Issue by KenjiPcx** [OrJDev/create-jd-app#98]
Hi, I am facing some issues when trying to use the private procedures for my trpc procedures, I am new to the t3 stack and I can't seem to get this to work, whenever I call private procedures, they fail to get the session and crash my application

I am not sure if I am calling it wrongly or not but I assume that it should work as long as I am logged in, tried wrapping it inside a <Show when={session()}> as well, please guide me 🙏🏼

I had been able to replicate this on postgres and on sqlite
1. clone a new example app from the create-jd-app
2. call a private procedure like the one in the example
```tsx
const secret = trpc.example.secret.useQuery();
...
<div>{secret.data}</div>
```
3. it breaks the page and the console shows the unauthorized 401 error
```
data: {
    code: 'UNAUTHORIZED',
    httpStatus: 401,
    stack: 'TRPCError: You are not authorized to access this resource\n
```

**Comment by OrJDev** [comment]
> Hi, I am facing some issues when trying to use the private procedures for my trpc procedures, I am new to the t3 stack and I can't seem to get this to work, whenever I call private procedures, they fail to get the session and crash my application
> 
> 
> 
> I am not sure if I am calling it wrongly or not but I assume that it should work as long as I am logged in, tried wrapping it inside a <Show when={session()}> as well, please guide me 🙏🏼
> 
> 
> 
> I had been able to replicate this on postgres and on sqlite
> 
> 1. clone a new example app from the create-jd-app
> 
> 2. call a private procedure like the one in the example
> 
> ```tsx
> 
> const secret = trpc.example.secret.useQuery();
> 
> ...
> 
> <div>{secret.data}</div>
> 
> ```
> 
> 3. it breaks the page and the console shows the unauthorized 401 error
> 
> ```
> 
> data: {
> 
>     code: 'UNAUTHORIZED',
> 
>     httpStatus: 401,
> 
>     stack: 'TRPCError: You are not authorized to access this resource\n
> 
> ```
> 
> 
> 
> 

Basically private procedures as their name suggest, will throw an error if the user is not logged in, it is an hidden resource, you can make it so it will only call this query if the user is logged in:

```ts
const session = createSession();
const secret = trpc.example.secret.useQuery(undefined, () => ({ enabled: !!session() }))
```

Using the enabled property, it will only make a request when the user is logged in

**Comment by OrJDev** [comment]
Closing this, feel free to reopen if you face an issue

**Comment by KenjiPcx** [comment]
Thanks for the tip, it works, looks like I got a lot more learning to do
